

ocoder:
	gcc -pg lab01-original-coder.c -lm -o toni_kukurin_o1

odecoder:
	gcc -pg lab01-original-decoder.c -lm -o toni_kukurin_o2

coder:
	gcc -I /opt/intel/ipp/include -L /opt/intel/ipp/lib/intel64_lin lab01-coder.c -lm -lippi -o toni_kukurin_1

decoder:
	gcc -I /opt/intel/ipp/include -L /opt/intel/ipp/lib/intel64_lin lab01-decoder.c -lm -lippi -o toni_kukurin_2

