
coder:
	gcc -I /opt/intel/ipp/include -L /opt/intel/ipp/lib/intel64_lin lab01-coder.c -lm -lippi -o toni_kukurin_1

decoder:
	gcc -I /opt/intel/ipp/include -L /opt/intel/ipp/lib/intel64_lin lab01-decoder.c -lm -lippi -o toni_kukurin_2
